version: '1'
services:
  nodejs-server:
    build: .
    restart: always
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  vue-test:
    build: .
    restart: always
    ports:
      - "8080:8080"
    container_name: vue-frontend-test
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules